## kitty config
###
## github.com/equk

# Fonts
font_family      JetBrains Mono Nerd Font
italic_font      JetBrains Mono Nerd Font
bold_font        JetBrains Mono Nerd Font
bold_italic_font JetBrains Mono Nerd Font

# Font size (in pts)
font_size        11.5

# Ligatures
disable_ligatures always

# Refresh rates
repaint_delay    0
input_delay      1
sync_to_monitor  no

# Style
window_border_width   0
cursor_blink_interval 0

# Disable bell
enable_audio_bell no
