## kitty config
###
## github.com/equk

# Fonts
# (disable italic fonts)
font_family      JetBrains Mono
italic_font      JetBrains Mono
bold_font        JetBrains Mono Bold
bold_italic_font JetBrains Mono Bold

# Font size (in pts)
font_size        11.5

# Ligatures
disable_ligatures always

# Nerd Fonts
# archlinux pkg: ttf-nerd-fonts-symbols-mono
symbol_map U+e000-U+e00a,U+e0a0-U+e0a2,U+e0a3,U+e0b0-U+e0b3,U+e0b4-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ea60-U+ec1e,U+ed00-U+efce,U+f000-U+f2ff,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font Mono

# Refresh rates
repaint_delay    0
input_delay      1
sync_to_monitor  no

# Style
window_border_width   0
cursor_blink_interval 0

# Disable bell
enable_audio_bell no

# Disable URLs
detect_urls no

# Disable Hyperlinks
allow_hyperlinks no

# DO NOT OPEN HYPERLINKS ON CLICK
mouse_map left click ungrabbed no-op

# Mouse Select
copy_on_select clipboard

# Mouse Paste
mouse_map right press ungrabbed paste_from_clipboard

# Color Theme
##

# main colors
background #232136
foreground #f8f8f2
cursor #bbbbbb
selection_background #44475a
selection_foreground #1e1f28

# black
color0 #000000
color8 #545454

# red
color1 #ff5555
color9 #ff5454

# green
color2 #50fa7b
color10 #50fa7b

# yellow
color3 #f0fa8b
color11 #f0fa8b

# blue
color4 #0d73cc
color12 #1a8fff

# magenta
color5 #ff78c5
color13 #ff78c5

# cyan
color6 #8ae9fc
color14 #8ae9fc

# white
color7 #bbbbbb
color15 #ffffff
