# ~/.config/alacritty/alacritty.yml
# Configuration for Alacritty, the GPU enhanced terminal emulator

env:
  TERM: xterm-256color

window:
  decorations: full
  padding:
    x: 2
    y: 2

draw_bold_text_with_bright_colors: true

font:
  normal:
    family: JetBrains Mono Nerd Font
  bold:
    family: JetBrains Mono Nerd Font
  italic:
    family: JetBrains Mono Nerd Font
  size: 11.5
  offset:
    x: 0
    y: -2
  glyph_offset:
    x: 0
    y: 0

debug.render_timer: false

# Colors (equilibriumuk)
colors:
  primary:
    background: '0x011627'
    foreground: '0xf8f8f2'
  normal:
    black:   '0x000000'
    red:     '0xff3333'
    green:   '0x00dd00'
    yellow:  '0xffff33'
    blue:    '0x0000aa'
    magenta: '0xff92d0'
    cyan:    '0x8be9fd'
    white:   '0xbbbbbb'
  bright:
    black:   '0x555555'
    red:     '0xff5555'
    green:   '0x55ff55'
    yellow:  '0xf1fa8c'
    blue:    '0x5555ff'
    magenta: '0xff79c6'
    cyan:    '0x55ffff'
    white:   '0xffffff'

bell:
  animation: EaseOutExpo
  duration: 100

window:
  opacity: 0.95

mouse_bindings:
  - { mouse: Middle, action: Paste }
  - { mouse: Right, action: Paste }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  faux_scrolling_lines: 1

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true


# break/disable hints (clickable url etc)
hints:
  enabled:
  - regex: ""
    command: echo
    post_processing: false
    mouse:
      enabled: false
      mods: Control

window.dynamic_title: true

cursor.style: Block
live_config_reload: true
