[theme]
name = "equk"

[colors]
AlertInfo = "#a6da95"
AlertWarn = "#eb6f92"
AlertError = "#f0fa8b"
Annotation = "#9ccfd8"
Base = "#ffffff"
Guidance = "#c3c3c3"
Important = "#e54270"
Title = "#3e8fb0"
