## tmux conf
###
## github.com/equk
###
# set window title
set-option -g set-titles on
# set 256 color
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
# enable mouse mode
set -g mouse on
# set scroll limit
set -g history-limit 30000
# rebind prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
# set statusbar
set -g status-position bottom
set -g status-interval 0
set -g status-style 'bg=#24273a fg=#cad3f5'
set -g base-index 1
# show date time on right
set -g status-right '%Y-%m-%d %H:%M '
# set window status
set -g window-status-activity-style 'bg=#b7bdf8,fg=#181926'
set -g window-status-bell-style 'bg=#eed49f,fg=#181926'
set -g window-status-current-style 'bg=#a6da95,fg=#24273a'
set -g window-status-format ' #I #W #F '
set -g window-status-current-format ' #I #W #F '
# set esc delay to 10ms
set-option -sg escape-time 10
# use wl-copy for clipboard
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"
# use mousewheel for scrolling
bind -T root WheelUpPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; copy-mode -e; send-keys -M"
bind -T root WheelDownPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; send-keys -M"
# unbind right click menu
unbind-key -T root MouseDown3Pane
# paste using right click
bind-key -T root MouseDown3Pane run -b "wl-paste -n | tmux load-buffer - ; tmux paste-buffer"
# new splits using meta key (alt)
bind -n M-n split-window -h
bind -n M-- split-window -v
bind -n M-| split-window -h
bind -n 'M-\' split-window -h
# close window
bind -n M-q kill-window
# switch panes
bind -n C-Left select-pane -L
bind -n C-Right select-pane -R
bind -n C-Up select-pane -U
bind -n C-Down select-pane -D
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R
