## tmux conf
###
## github.com/equk
###
# set window title
set-option -g set-titles on
# set 256 color
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
# enable mouse mode
set -g mouse on
# set scroll limit
set -g history-limit 30000
# rebind prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
# disable automatic window rename
set-window-option -g automatic-rename off
# set statusbar
set -g status-position bottom
set -g status-interval 0
set -g status-style 'bg=#24273a fg=#cad3f5'
set -g base-index 1
# show date time on right
set -g status-right '%Y-%m-%d %H:%M '
# set window status
set -g window-status-activity-style 'bg=#b7bdf8,fg=#181926'
set -g window-status-bell-style 'bg=#eed49f,fg=#181926'
set -g window-status-current-style 'bg=#a6da95,fg=#24273a'
set -g window-status-format ' #I #W #F '
set -g window-status-current-format ' #I #W #F '
# set pane options
set -g pane-border-style 'fg=#a6da95'
# set esc delay to 10ms
set-option -sg escape-time 10
# use wl-copy for clipboard
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"
# use mousewheel for scrolling
bind -T root WheelUpPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; copy-mode -e; send-keys -M"
bind -T root WheelDownPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; send-keys -M"
# unbind right click menu
unbind-key -T root MouseDown3Pane
# paste using right click
bind-key -T root MouseDown3Pane run -b "wl-paste -n | tmux load-buffer - ; tmux paste-buffer"
# new splits using meta key (alt)
bind -n M-- split-window -v
bind -n M-| split-window -h
bind -n 'M-\' split-window -h
# new window
bind -n M-n command-prompt -p "window name:" "new-window; rename-window '%%'"
# close window
bind -n M-q kill-window
# switch panes
# re: github.com/christoomey/vim-tmux-navigator
# check for vim
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | /usr/bin/grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?\.?(view|n?vim?x?)(-wrapped)?(diff)?$'"
# if vim send keys
# otherwise select pane
# hjkl keys
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
# arrow keys
bind-key -n 'C-Left' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-Down' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-Up' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-Right' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
bind-key -T copy-mode-vi 'C-Left' select-pane -L
bind-key -T copy-mode-vi 'C-Down' select-pane -D
bind-key -T copy-mode-vi 'C-Up' select-pane -U
bind-key -T copy-mode-vi 'C-Right' select-pane -R

